
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    prefer_const_constructors: ignore
    use_build_context_synchronously: ignore
    use_key_in_widget_constructors: ignore
include: package:flutter_lints/flutter.yaml

linter:

  rules:
